plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

base {
    archivesName = 'abcdlogin'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }
        client {}
        server {}
    }
    mods {
        abcdlogin {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
